name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Container
        run: docker compose up -d

      - name: Test Container
        run: docker compose exec web uv run pytest -s

      - name: Run pre-commit checks
        run: docker compose exec web uv run pre-commit run --all-files
